package comm

import (
	"fmt"
	"os"

	"github.com/ubax/ubax-pilot/pkg/logger"
)

// ConfigRenderer translates server-side abstract rules into collector-specific config files
type ConfigRenderer struct {
	collectorType string
	configPath    string
}

// NewConfigRenderer creates a new config renderer
func NewConfigRenderer(collectorType, configPath string) *ConfigRenderer {
	return &ConfigRenderer{
		collectorType: collectorType,
		configPath:    configPath,
	}
}

// Render generates the collector configuration file from server rules
func (cr *ConfigRenderer) Render(rules []byte) error {
	var content string

	switch cr.collectorType {
	case "vector":
		content = cr.renderVectorConfig(rules)
	case "filebeat":
		content = cr.renderFilebeatConfig(rules)
	default:
		return fmt.Errorf("unsupported collector type: %s", cr.collectorType)
	}

	if err := os.WriteFile(cr.configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	logger.Info("Config rendered to:", cr.configPath)
	return nil
}

// renderVectorConfig generates vector.toml configuration
func (cr *ConfigRenderer) renderVectorConfig(rules []byte) string {
	// TODO: Parse server rules and generate vector TOML config
	return `# Generated by UBAX-Pilot
data_dir = "/var/lib/vector"

[sources.app_logs]
type = "file"
include = ["/var/log/app/*.log"]

[sinks.ubax_output]
type = "http"
inputs = ["app_logs"]
uri = "http://server:8080/ingest"
encoding.codec = "json"
`
}

// renderFilebeatConfig generates filebeat.yml configuration
func (cr *ConfigRenderer) renderFilebeatConfig(rules []byte) string {
	// TODO: Parse server rules and generate filebeat YAML config
	return `# Generated by UBAX-Pilot
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/*.log

output.http:
  hosts: ["http://server:8080"]
`
}

// TriggerHotReload signals the collector to reload its configuration
func (cr *ConfigRenderer) TriggerHotReload() error {
	// TODO: Send SIGHUP to collector process or call reload API
	logger.Info("Triggering hot reload for:", cr.collectorType)
	return nil
}
